Add multicode doc to POS
TransbankDevelopers/transbank-developers-docs pull request #288
Opened 2020-11-26 15:53 UTC by afiebig

2020-11-26 15:54 UTC, gonzunigad commented on documentacion/posintegrado/README.md
> +// Ej: Transbank.POS.connect(...); en vez de POS.connect(...) como se especifica en los ejemplos de mas abajo.
¿Me recomendabas dejar esto en una nota? ¿Me ayudas con eso?

2020-11-26 16:02 UTC, afiebig commented on documentacion/posintegrado/README.md
> +<aside class="notice">
@gonzunigad aquí había dejado la nota. pero la agregua arriba también.

2020-11-26 16:06 UTC, gonzunigad requested changes
código con tilde 100 veces en la pizarra @afiebig :)

2020-11-26 16:06 UTC, gonzunigad commented on documentacion/posintegrado/README.md
> +- `CodigoDeComercio`: Codigo de comercio que realiza la venta. (No es el mismo codigo del POS, ya que en multicodigo el codigo padre no puede realizar ventas.)
```suggestion
- `CodigoDeComercio`: Código de comercio que realiza la venta. (No es el mismo código del POS, ya que en multicódigo el código padre no puede realizar ventas.)
```

2020-11-26 16:06 UTC, gonzunigad commented on documentacion/posintegrado/README.md
> +En el caso de C#, los mensajes intermedios se reciven mediante el evento `IntermediateResponseChange` y el argumento retornado es de tipo `IntermediateResponse`
```suggestion
En el caso de C#, los mensajes intermedios se reciben mediante el evento `IntermediateResponseChange` y el argumento retornado es de tipo `IntermediateResponse`
```

2020-11-26 16:06 UTC, gonzunigad commented on documentacion/posintegrado/README.md
> +Si usas mensajes intermedios en Javascript, entonces puedes pasar un callback como tercer parametro.
```suggestion
Si usas mensajes intermedios en Javascript, entonces puedes pasar un callback como tercer parámetro.
```

2020-11-26 16:06 UTC, gonzunigad commented on documentacion/posintegrado/README.md
> +//Este tercer parametro es opcional. Si está presente, se ejecutará cada vez que llegue un mensaje de status de la venta.
```suggestion
//Este tercer parámetro es opcional. Si está presente, se ejecutará cada vez que llegue un mensaje de status de la venta.
```

2020-11-26 16:06 UTC, gonzunigad commented on documentacion/posintegrado/README.md
> +Si el POS recibe el comando de Última Venta y no existen transacciones en memoria del POS, se envía la respuesta a la caja indicando el código de respuesta 11.
```suggestion
Si el POS recibe el comando de última venta y no existen transacciones en memoria del POS, se envía la respuesta a la caja indicando el código de respuesta 11.
```

2020-11-26 16:06 UTC, gonzunigad commented on documentacion/posintegrado/README.md
> +  "Accounting Date": "28/10/2019 22:35:12";
```suggestion
  "Accounting Date": "28/10/2019 22:35:12",
```

2020-11-26 16:06 UTC, gonzunigad commented on documentacion/posintegrado/README.md
> +Esta transacción solicita al POS **todas** las transacciones que se han realizado y permanecen en la memoria del POS. El parámetro que recibe esta función es de tipo booleano e indica si se realiza l
```suggestion
Esta transacción solicita al POS **todas** las transacciones que se han realizado y permanecen en la memoria del POS. El parámetro que recibe esta función es de tipo booleano e indica si se realiza la impresión del detalle en el POS. En el caso de que no se solicite la impresión, el POS envía **todas** las transacciones a la caja, una por una. Si se realiza la impresión, la caja recibirá una lista vacía de transacciones.
```

2020-11-26 16:06 UTC, gonzunigad commented on referencia/posintegrado/README.md
> +Este comando es enviado por la caja para solicitar la ejecución de una venta para los distintos codigos de comercio asociados en el POS. Solo los codigos de comercios virtuales o hijos puede realizar
```suggestion
Este comando es enviado por la caja para solicitar la ejecución de una venta para los distintos códigos de comercio asociados en el POS. Solo los códigos de comercios virtuales o hijos puede realizar ventas, el código de comercio del POS es distinto y no puede realizar ventas. Los siguientes parámetros deben ser enviados desde la caja:
```

2020-11-26 16:06 UTC, gonzunigad commented on referencia/posintegrado/README.md
> +- `Comercio prestador`: Es el codigo de comercio que ejecutara la venta.
```suggestion
- `Comercio prestador`: Es el código de comercio que ejecutara la venta.
```

2020-11-26 16:06 UTC, gonzunigad commented on referencia/posintegrado/README.md
> +- Los mensajes intermedios que envía el POS y que deben ser mostrados por la Caja, deben corresponder según los siguientes códigos:
```suggestion
- Los mensajes intermedios que envía el POS y que deben ser mostrados por la caja, deben corresponder según los siguientes códigos:
```

2020-11-26 16:08 UTC, gonzunigad requested changes

2020-11-26 16:08 UTC, gonzunigad commented on producto/posintegrado/README.md
> +- Venta multicodigo.
```suggestion
- Venta multicódigo.
```

2020-11-26 16:08 UTC, gonzunigad commented on producto/posintegrado/README.md
> +- Ultima venta multicodigo
```suggestion
- Ultima venta multicódigo
```

2020-11-26 16:08 UTC, gonzunigad commented on producto/posintegrado/README.md
> +- Detalle de ventas multicodigo.
```suggestion
- Detalle de ventas multicódigo.
```

2020-11-26 20:20 UTC, afiebig commented
> código con tilde 100 veces en la pizarra @afiebig :)

Si los texto de multicódigo tienen pifias también esta malos los normales, por que son copy paste

2020-11-26 20:23 UTC, afiebig commented on documentacion/posintegrado/README.md
> +<script src="https://unpkg.com/transbank-pos-sdk-web@1/dist/pos.js"></script>
ahora que lo mencionas, no es 2.1.0?

2020-11-28 03:17 UTC, gonzunigad commented on documentacion/posintegrado/README.md
> +<script src="https://unpkg.com/transbank-pos-sdk-web@1/dist/pos.js"></script>
Si, podría ser 2.1, aunque si pones solo 2, se usa el 2.X más alto automáticamente :)

2020-12-01 14:32 UTC, gonzunigad approved these changes
👌

2020-12-01 14:33 UTC, merged